---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sd10.
--- DateTime: 2026/1/4 16:16
---
if(redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0